services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .dev.env
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
  #     - redis
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis:/data
  postgres:
    image: postgres
    restart: always
    env_file:
      - .dev.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-postgres:/var/lib/postgresql/data
volumes:
# redis:
#   driver: local
  docker-postgres:
