# name: Node.js CI

# on:
#   push:
#     branches:
#       - main
#   pull-request:
#     branches:
#       - main

# env:
#   CI: true

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Use Node.js 14.x
#         uses: akhileshns/heroku-deploy@v3.12.12